"""ORFaqs Protein Discovery Data Models"""

import pathlib
from pydantic import (
    BaseModel,
    ConfigDict,
    FilePath,
    Field,
    field_validator,
)
from typing import Annotated, List, Literal, Optional
from orfaqs.libs.python.core.nucleotides import (
    GenomicSequence,
    StrandType,
)
from orfaqs.libs.python.core.codons import Codon
from orfaqs.libs.python.core.ribosomes import (
    RNAReadingFrame,
)

from orfaqs.libs.python.utils.pandasutils import (
    DataFrameExportFormat,
    DataFrameExportFormatOptions,
)


_AVAILABLE_EXPORT_FORMATS: list[str] = [
    format for format in DataFrameExportFormatOptions.__args__
]


class DiscoverProteinsDataModel:
    """DiscoverProteinsDataModel"""

    GENOMIC_SEQUENCE_ARG_NAME = 'genomic_sequence'
    UID_ARG_NAME = 'uid'
    STRAND_TYPE_ARG_NAME = 'strand_type'
    FRAMES_ARG_NAME = 'frames'
    START_CODONS_ARG_NAME = 'start_codons'
    STOP_CODONS_ARG_NAME = 'stop_codons'
    INCLUDE_REVERSE_COMPLEMENT_ARG_NAME = 'include_reverse_complement'
    EXPORT_RESULTS_ARG_NAME = 'export_results'
    OUTPUT_DIRECTORY_ARG_NAME = 'output_directory'
    JOB_ID = 'job_id'
    EXPORT_FORMAT = 'export_format'
    ENABLE_GPU = 'enable_gpu'
    DISPLAY_PROGRESS = 'display_progress'

    class ArgsModel(BaseModel):
        """Model"""

        model_config = ConfigDict(
            arbitrary_types_allowed=True,
            extra='ignore',
        )
        genomic_sequence: Annotated[
            FilePath | GenomicSequence | str,
            Field(
                description=(
                    'A FASTA sequence file, GenomicSequence object, or '
                    'genomic sequence string.',
                )
            ),
        ] = None
        uid: Annotated[
            Optional[str],
            Field(
                description=(
                    'Defines the accession number associated with the input'
                    'sequence string. If the input sequence is a file, this '
                    'option is ignored.'
                ),
            ),
        ] = None
        strand_type: Annotated[
            Optional[StrandType],
            Field(
                description=(
                    'The strand type of the sequence being processed.'
                ),
            ),
        ] = None
        frames: Annotated[
            Optional[List[RNAReadingFrame]],
            Field(
                description=(
                    'The reading frame of the sequence being processed.'
                ),
            ),
        ] = None
        start_codons: Annotated[
            Optional[List[Codon]],
            Field(
                description=(
                    'The start codons to consider during translation.'
                ),
            ),
        ] = None
        stop_codons: Annotated[
            Optional[List[Codon]],
            Field(
                description=(
                    'The stop codons to consider during translation.'
                ),
            ),
        ] = None
        include_reverse_complement: Annotated[
            Optional[bool],
            Field(
                description=(
                    'Include translation of the reverse complement of the '
                    'provided sequence(s) during discovery.'
                ),
            ),
        ] = True
        export_results: Annotated[
            Optional[bool],
            Field(
                description=('Export the discovered proteins to file.'),
            ),
        ] = False
        output_directory: Annotated[
            Optional[pathlib.Path],
            Field(
                description=(
                    'The output directory for exported files and results. If '
                    'the path does not exist, one will be created.'
                ),
            ),
        ] = None
        job_id: Annotated[
            Optional[str],
            Field(
                description=(
                    'A string used to uniquely identify a set of results '
                    'generated by the tool. All results with the same job_id '
                    'share the same parent path.'
                ),
            ),
        ] = None
        export_format: Annotated[
            Optional[DataFrameExportFormatOptions],
            Field(
                description=('Define the format of the exported data.'),
                default=DataFrameExportFormat.CSV,
            ),
        ] = None
        enable_gpu: Annotated[
            Optional[bool],
            Field(
                description=(
                    'Use available GPU resources for processing. If supported '
                    'GPU resources cannot be found, processing defaults to '
                    'the CPU.'
                ),
            ),
        ] = True
        display_progress: Annotated[
            Optional[bool],
            Field(
                description=(
                    'Display progress information (such as progress bars, '
                    'update statements, etc.) while executing commands.'
                ),
            ),
        ] = False

        @classmethod
        def _validate_codons(cls, codons: list[Codon]) -> list[Codon]:
            if (
                not isinstance(codons, list)
                or codons == ['']
                or len(codons) == 0
            ):
                return None

            return codons

        @field_validator('genomic_sequence', mode='before')
        @classmethod
        def validate_genomic_sequence(
            cls,
            genomic_sequence: (FilePath | GenomicSequence),
        ) -> any:
            if isinstance(genomic_sequence, GenomicSequence):
                return genomic_sequence.sequence_str
            return genomic_sequence

        @field_validator('frames', mode='before')
        @classmethod
        def validate_frames(
            cls,
            reading_frames: list[RNAReadingFrame | int],
        ) -> list[RNAReadingFrame]:
            if (
                not isinstance(reading_frames, list)
                or reading_frames == ''
                or reading_frames == ['']
                or len(reading_frames) == 0
            ):
                return None

            return reading_frames

        @field_validator('start_codons', mode='before')
        @classmethod
        def validate_start_codons(
            cls,
            start_codons: list[Codon],
        ) -> list[RNAReadingFrame]:
            return cls._validate_codons(start_codons)

        @field_validator('stop_codons', mode='before')
        @classmethod
        def validate_stop_codons(
            cls,
            stop_codons: list[Codon],
        ) -> list[RNAReadingFrame]:
            return cls._validate_codons(stop_codons)

    @staticmethod
    def arg_names() -> list[str]:
        return DiscoverProteinsDataModel.ArgsModel.model_fields.keys()

    @staticmethod
    def kwargs() -> dict[str, any]:
        args_names = DiscoverProteinsDataModel.arg_names()
        arg_values = len(args_names) * [None]
        return dict(zip(args_names, arg_values))

    @staticmethod
    def export_format_options() -> Literal[str]:
        return DataFrameExportFormatOptions

    @staticmethod
    def available_export_formats() -> list[str]:
        return _AVAILABLE_EXPORT_FORMATS
