#!/usr/bin/env python
"""
ORFaqs Protein Analysis
"""

import enum
import logging
import pathlib

from enum import Enum

from orfaqs.apps.common.cliutils import CliUtil
from orfaqs.apps.common.orfaqsapp import ORFaqsApp
from orfaqs.apps.common.orfaqsproteinquery import ORFaqsProteinQueryUtils


from orfaqs.lib.utils.directoryutils import DirectoryUtils
from orfaqs.lib.utils.perfutils import PerfProfiler

_logger = logging.getLogger(__name__)

_perf_profiler = PerfProfiler(__name__)


class _ProfilingFunctionName(Enum):
    PROTEIN_ANALYSIS_USER_QUERY = enum.auto()


class ORFaqsProteinQuery(ORFaqsApp):
    """ORFaqsProteinQuery"""

    _RESULTS_FILE_NAME = 'protein-analysis'
    _DEFAULT_WORKSPACE = 'orfaqs_protein_query'

    @staticmethod
    def program_name():
        return 'ORFaqs Protein Query'

    @staticmethod
    def cli():
        try:
            arg_descriptor_list = [
                CliUtil.create_new_arg_descriptor(
                    ('-i', '--input_proteins'),
                    arg_help=(
                        'A protein sequence string, file, or ORFaqs '
                        'discovered proteins directory. Additional '
                        'information regarding specific input requirements '
                        'is specified in relevant option descriptions.'
                    ),
                    arg_type=str,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-j', '--job_id'),
                    arg_help=(
                        'A string used to uniquely identify a set of '
                        'results generated by the tool. All results '
                        'with the same job_id share the same directory '
                        'sub-folder.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-w', '--workspace'),
                    arg_help=(
                        'A string used to name a unique user defined '
                        'workspace. The workspace name is also used to name '
                        'any databases created on behalf of operations '
                        'performed within the workspace sessions. Workspace '
                        'names must be alphanumeric [Aa-Zz, 0-9]. The '
                        'underscore character "_" is permitted.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-o', '--output_directory'),
                    arg_help=(
                        'The output directory for exported files '
                        'and results. If the path does not exist, one '
                        'will be created. The default directory is: '
                        f'{ORFaqsProteinQuery.default_output_directory()}'
                    ),
                    arg_type=str,
                    default=ORFaqsProteinQuery.default_output_directory(),
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-l', '--load_proteins'),
                    arg_help=(
                        'If enabled, this option loads protein data into the '
                        'specified workspace database. '
                        'Specify the workspace using the (-w, --workspace) '
                        'option, and provide protein input data using the '
                        '(-i, --input_proteins) option.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--remove_workspace'),
                    arg_help=(
                        'If enabled, the specified workspace and any '
                        'associated databases and resources are removed.'
                        'Provide the workspace using the (-w, --workspace) '
                        'option. **Note**: Use of this option drops all '
                        'other options and actions from execution.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--force_load'),
                    arg_help=(
                        'If enabled, data with the workspace is replaced with '
                        'the current data referenced by the input path. '
                        'Otherwise, any duplicate data is dropped and any '
                        'non-duplicate data is added to the workspace.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-q', '--query'),
                    arg_help=(
                        'Query string for inspecting the protein sequence '
                        'or set of sequences specified in the input.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    (f'--{ORFaqsApp.launch_json_option_name()}'),
                    arg_help=(
                        'A JSON file specifying arguments and options to '
                        "apply to the program's session. If "
                        'arguments provided in the JSON overlap with '
                        'arguments provided on the command line, values from '
                        'the command line override those specified in the JSON.'
                    ),
                    arg_type=str,
                ),
            ]

            cli_arg_parser = CliUtil.create_arg_parser(
                arg_descriptor_list,
                program_name=ORFaqsProteinQuery.program_name(),
                description=(
                    'Analyze proteins sequences or collections of sequences.'
                ),
                epilog='',
            )

            # Process the CLI args and incorporate any
            # values set in the launch json.
            ui_kwargs = ORFaqsApp.process_ui_kwargs(
                **CliUtil.parse_args(cli_arg_parser)
            )
            if 'input_proteins' not in ui_kwargs:
                message = (
                    '[ERROR] No input sequence string, file, or directory was '
                    'specified. A valid input is required.'
                )
                _logger.error(message)
                cli_arg_parser.print_help()
            else:
                ORFaqsProteinQuery.run(**ui_kwargs)

        except SystemExit as e:
            if e.args[0] is True:
                raise SystemExit from e

    @staticmethod
    def _remove_workspace(
        workspace: str,
        **kwargs,
    ):
        ORFaqsProteinQueryUtils.remove_workspace(workspace)

    @staticmethod
    def _load_proteins(
        workspace: str,
        input_proteins: str | pathlib.Path,
        force_load: bool,
        **kwargs,
    ):
        if workspace is None:
            workspace = ORFaqsProteinQuery._DEFAULT_WORKSPACE
        ORFaqsProteinQueryUtils.load_discovered_proteins(
            workspace=workspace,
            input_path=input_proteins,
            force_load=force_load,
        )

    @staticmethod
    def _run(
        output_directory: str | pathlib.Path,
        job_id: str = None,
        load_proteins: bool = False,
        remove_workspace: bool = False,
        **kwargs,
    ):
        if output_directory is None:
            output_directory = ORFaqsProteinQuery.default_output_directory()

        # Create the local output directory and output file path
        output_directory = DirectoryUtils.make_path_object(output_directory)
        if isinstance(job_id, str):
            output_directory = output_directory.joinpath(job_id)

        if remove_workspace:
            ORFaqsProteinQuery._remove_workspace(**kwargs)
            return

        if load_proteins:
            ORFaqsProteinQuery._load_proteins(**kwargs)


if __name__ == '__main__':
    ORFaqsProteinQuery.cli()
