#!/usr/bin/env python
"""
ORFaqs Protein Query
"""

import logging
import os


from orfaqs.lib.python.utils.cliutils import CliUtil
from orfaqs.modules.python.common.orfaqscli import ORFaqsCli
from orfaqs.modules.python.proteinquery.orfaqsproteinquery import (
    ORFaqsProteinQueryApi,
)


from orfaqs.lib.python.utils.directoryutils import DirectoryUtils


_logger = logging.getLogger(__name__)


class ORFaqsProteinQuery(ORFaqsCli):
    """ORFaqsProteinQuery"""

    _RESULTS_FILE_NAME = 'protein-query'
    _DEFAULT_WORKSPACE = 'orfaqs_protein_query'

    @staticmethod
    def program_name():
        return 'ORFaqs Protein Query'

    @staticmethod
    def at_least_one_expected_options():
        return [
            'export_file_path',
            'export_format',
            'load_proteins',
            'query',
            'remove_workspace',
            'remove_table',
        ]

    @staticmethod
    def cli():
        try:
            args_list = [
                CliUtil.create_new_arg_descriptor(
                    ('-j', '--job_id'),
                    arg_help=(
                        'A string used to uniquely identify a set of '
                        'results generated by the tool. All results '
                        'with the same job_id share the same directory '
                        'sub-folder.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-w', '--workspace'),
                    arg_help=(
                        'A string used to name a unique user defined '
                        'workspace. The workspace name is also used to name '
                        'any databases created on behalf of operations '
                        'performed within the workspace sessions. Workspace '
                        'names must be alphanumeric [Aa-Zz, 0-9]. The '
                        'underscore character "_" is permitted. The default '
                        'workspace is: '
                        f'{ORFaqsProteinQuery._DEFAULT_WORKSPACE}.'
                    ),
                    arg_type=str,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-o', '--output_directory'),
                    arg_help=(
                        'The output directory for exported files '
                        'and results. If the path does not exist, one '
                        'will be created. The default directory is: '
                        f'{ORFaqsProteinQuery.default_output_directory()}'
                    ),
                    arg_type=str,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--export'),
                    arg_help=(
                        'If enabled, data from the specified workspace and '
                        'table will be exported. '
                        'Provide the workspace using the (-w, --workspace) '
                        'option and the table using the (-t, --table) option. '
                        'Otherwise, the default workspace and table are '
                        'exported.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--export_file_path'),
                    arg_help=(
                        'The file path where workspace data is exported. If '
                        'an operation is expected to export data, and no '
                        'export path is given, the file will be created in '
                        'output directory with the file name: '
                        f'{ORFaqsProteinQueryApi.default_export_file_name()}.'
                    ),
                    arg_type=str,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--export_format'),
                    arg_help=(
                        'Defines the exported format of the resulting data. '
                        'The default format is '
                        f'{ORFaqsProteinQueryApi.default_export_format()}'
                        'Supported formats are: '
                        f'{ORFaqsProteinQueryApi.available_export_formats()}.'
                    ),
                    arg_type=str,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--remove_workspace'),
                    arg_help=(
                        'If enabled, the specified workspace and any '
                        'associated databases and resources are removed.'
                        'Provide the workspace using the (-w, --workspace) '
                        'option. **Note**: Use of this option drops all '
                        'other options and actions from execution.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('--remove_table'),
                    arg_help=(
                        'If enabled, the specified workspace database table '
                        'is removed. Provide the workspace using the '
                        '(-w, --workspace) option and the database table using '
                        'the (-t, --table_name) option. '
                        '**Note**: Use of this option drops all '
                        'other options and actions from execution.'
                    ),
                    action='store_true',
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-q', '--query'),
                    arg_help=(
                        'Query string for inspecting the protein sequence '
                        'or set of sequences specified in the input.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-l', '--load_proteins'),
                    arg_help=(
                        'A protein file, or directory containing protein '
                        'data. Data is loaded into the specified workspace '
                        'and database table. Provide the workspace using the '
                        '(-w, --workspace) option and the table using the '
                        '(-t, --table) option.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    ('-t, --table'),
                    arg_help=(
                        'The name to give the table created for storing the '
                        'data specified in (-l, --load_proteins) command.'
                    ),
                    arg_type=str,
                    default=None,
                ),
                CliUtil.create_new_arg_descriptor(
                    (f'--{ORFaqsCli.launch_json_option_name()}'),
                    arg_help=(
                        'A JSON file specifying arguments and options to '
                        'apply to the program session. If arguments provided '
                        'in the JSON overlap with arguments provided on the '
                        'command line, values from the command line override '
                        'those specified in the JSON.'
                    ),
                    arg_type=str,
                ),
            ]

            cli_arg_parser = CliUtil.create_arg_parser(
                args_list,
                program_name=ORFaqsProteinQuery.program_name(),
                description=(
                    'Run queries on collections of protein sequences.'
                ),
                epilog='',
            )

            # Process the CLI args and incorporate any
            # values set in the launch json.
            ui_kwargs = ORFaqsCli.process_ui_kwargs(
                **CliUtil.parse_args(cli_arg_parser)
            )
            valid_args = False
            expected_options = (
                ORFaqsProteinQuery.at_least_one_expected_options()
            )
            for option in expected_options:
                arg_value = ui_kwargs.get(option)
                if isinstance(arg_value, bool) and (not arg_value):
                    arg_value = None
                if arg_value is not None:
                    valid_args = True
                    break

            if not valid_args:
                message = (
                    '[ERROR] Not enough inputs were provided for the '
                    'application to continue. At lease ONE of the following '
                    f'options must be specified: {expected_options}'
                )
                _logger.error(message)
                cli_arg_parser.print_help()
            else:
                ORFaqsProteinQuery.run(**ui_kwargs)

        except SystemExit as e:
            if e.args[0] is True:
                raise SystemExit from e

    @staticmethod
    def _remove_workspace(workspace: str):
        ORFaqsProteinQueryApi.remove_workspace(workspace)

    @staticmethod
    def _remove_table(
        workspace: str,
        table_name: str,
    ):
        ORFaqsProteinQueryApi.remove_table(
            workspace=workspace,
            table_name=table_name,
        )

    @staticmethod
    def _load_proteins(
        workspace: str,
        table_name: str,
        input_path: (str | os.PathLike),
        **kwargs,
    ):
        ORFaqsProteinQueryApi.load_proteins(
            workspace=workspace,
            table_name=table_name,
            input_path=input_path,
        )

    @staticmethod
    def _export_proteins(
        workspace: str,
        table_name: str,
        export_file_path: (str | os.PathLike),
        export_format: str,
        query: str,
        **kwargs,
    ):
        ORFaqsProteinQueryApi.export_proteins(
            workspace=workspace,
            table_name=table_name,
            export_path=export_file_path,
            export_format=export_format,
            query_condition=query,
        )

    @staticmethod
    def _run(
        output_directory: (str | os.PathLike),
        job_id: str = None,
        workspace: str = None,
        table_name: str = None,
        export: bool = None,
        load_proteins: str = None,
        remove_workspace: bool = False,
        remove_table: bool = False,
        **kwargs,
    ):
        if output_directory is None:
            output_directory = './'

        output_directory = DirectoryUtils.make_path_object(output_directory)
        output_directory = output_directory.joinpath(
            ORFaqsProteinQuery.default_output_directory()
        )

        # Create the local output directory and output file path.
        output_directory = DirectoryUtils.make_path_object(output_directory)
        if isinstance(job_id, str):
            output_directory = output_directory.joinpath(job_id)
        DirectoryUtils.mkdir_path(output_directory)

        # Set the default workspace if none is provided.
        if workspace is None:
            workspace = ORFaqsProteinQuery._DEFAULT_WORKSPACE
        #######################################################################
        # Remove workspace
        if remove_workspace:
            ORFaqsProteinQuery._remove_workspace(workspace)
            return
        #######################################################################
        # Remove workspace table
        if remove_table:
            ORFaqsProteinQuery._remove_table(
                workspace=workspace,
                table_name=table_name,
            )
            return

        #######################################################################
        # Load proteins...
        if load_proteins is not None:
            ORFaqsProteinQuery._load_proteins(
                workspace=workspace,
                table_name=table_name,
                input_path=load_proteins,
                **kwargs,
            )

        #######################################################################
        # Export proteins conditions...
        if (
            export
            or (kwargs.get('export_file_path') is not None)
            or (kwargs.get('export_format') is not None)
        ):
            export_file_path = kwargs.get('export_file_path')
            if export_file_path is None:
                export_file_path = (
                    output_directory
                    / ORFaqsProteinQueryApi.default_export_file_name()
                )
                kwargs['export_file_path'] = export_file_path
            ORFaqsProteinQuery._export_proteins(
                workspace=workspace,
                table_name=table_name,
                **kwargs,
            )


if __name__ == '__main__':
    ORFaqsProteinQuery.cli()
