"""
Protein discovery route module for the ORFaqs REST API.

This module provides API endpoints for discovering proteins from genomic
sequences.

It supports input from direct sequence strings or uploaded files, with
configurable reading frames, start/stop codons, and export formats.
Results are streamed as compressed archives for download.
"""

from fastapi import (
    APIRouter,
    BackgroundTasks,
    File,
    Form,
    UploadFile,
)
from typing import (
    Annotated,
    List,
    Optional,
)
from orfaqs.backend.python.orfaqsrestapi.app.api.configuration import (
    orfaqs_rest_api_settings,
)
from orfaqs.backend.python.orfaqsrestapi.app.core.utils.responseutils import (
    ResponseUtils,
)
from orfaqs.libs.python.utils.directoryutils import DirectoryUtils
from orfaqs.libs.python.utils.pandasutils import (
    DataFrameExportFormat,
)
from orfaqs.modules.python.orfaqsproteindiscovery.orfaqsproteindiscovery import (
    ORFaqsProteinDiscoveryApi,
    DiscoverProteinsDataModel,
    RNAReadingFrame,
    StrandType,
)


class RouteSettings:
    ROUTE_NAME: str = 'discoverproteins'
    ROUTE_ENDPOINT: str = f'/{ROUTE_NAME}'
    OUTPUT_DIRECTORY: str = (
        f'{orfaqs_rest_api_settings.ROUTE_NAME}{ROUTE_ENDPOINT}'
    )
    DOWNLOAD_FILE_NAME: str = 'orfaqs-discovered-proteins.zip'
    DISPLAY_PROGRESS: bool = False


router = APIRouter(tags=[RouteSettings.ROUTE_ENDPOINT])


@router.post(RouteSettings.ROUTE_ENDPOINT)
async def discover_proteins(
    user_id: Annotated[
        str,
        Form(description='The user id associated with the current session.'),
    ],
    genomic_sequence: Annotated[
        Optional[str],
        Form(description=('A genomic sequence string')),
    ] = None,
    file: Annotated[
        Optional[UploadFile],
        File(...),
    ] = None,
    uid: Annotated[
        Optional[str],
        Form(
            description=(
                'Defines the accession number associated with the input'
                'sequence string. If the input sequence is a file, this '
                'option is ignored.'
            ),
        ),
    ] = None,
    strand_type: Annotated[
        Optional[StrandType],
        Form(
            description=('The strand type of the sequence being processed.'),
        ),
    ] = None,
    frames: Annotated[
        Optional[List[RNAReadingFrame | str]],
        Form(
            description=('The reading frame of the sequence being processed.'),
        ),
    ] = None,
    start_codons: Annotated[
        Optional[List[str]],
        Form(
            description=('The start codons to consider during translation.'),
        ),
    ] = None,
    stop_codons: Annotated[
        Optional[List[str]],
        Form(
            description=('The stop codons to consider during translation.'),
        ),
    ] = None,
    include_reverse_complement: Annotated[
        Optional[bool],
        Form(
            description=(
                'Include translation of the reverse complement of the '
                'provided sequence(s) during discovery.'
            ),
        ),
    ] = True,
    job_id: Annotated[
        Optional[str],
        Form(
            description=(
                'A string used to uniquely identify a set of results '
                'generated by the tool. All results with the same job_id '
                'share the same parent path.'
            ),
        ),
    ] = None,
    export_format: Annotated[
        Optional[DiscoverProteinsDataModel.export_format_options()],
        Form(
            description=('Define the format of the exported data.'),
        ),
    ] = DataFrameExportFormat.CSV,
    background_tasks: BackgroundTasks = None,
):
    # Create a temporary directory. This will store intermediate data as well
    # as the data for request.
    temporary_directory = DirectoryUtils.temporary_directory()
    processing_directory_path = DirectoryUtils.make_path_object(
        temporary_directory
    )
    if file is not None:
        # Save the file in the processing directory.
        file_path = processing_directory_path / file.filename
        temporary_file_path = DirectoryUtils.save_as_file(
            file_path,
            file.file,
            binary_data=True,
        )
        genomic_sequence = temporary_file_path

    output_directory = (
        processing_directory_path / RouteSettings.OUTPUT_DIRECTORY
    )
    discover_proteins_args_model = DiscoverProteinsDataModel.ArgsModel(
        genomic_sequence=genomic_sequence,
        uid=uid,
        strand_type=strand_type,
        frames=frames,
        start_codons=start_codons,
        stop_codons=stop_codons,
        include_reverse_complement=include_reverse_complement,
        export_results=True,
        job_id=job_id,
        output_directory=output_directory,
        export_format=export_format,
        display_progress=RouteSettings.DISPLAY_PROGRESS,
    )

    ORFaqsProteinDiscoveryApi.discover_proteins(discover_proteins_args_model)

    # Remove all temporary data after the request is complete.
    background_tasks.add_task(
        DirectoryUtils.cleanup_temporary_directory,
        temporary_directory,
    )
    download_file_name = RouteSettings.DOWNLOAD_FILE_NAME
    if job_id is not None:
        download_file_name = f'{download_file_name}-{job_id}'
    return ResponseUtils.stream_response_from_directory_path(
        directory_path=output_directory,
        download_file_name=download_file_name,
    )
