"""
Orfaqs App
"""

import enum
import pathlib
import typer

from typing import Callable

from orfaqs.lib.python.utils.directoryutils import DirectoryUtils

from abc import ABC, abstractmethod

from orfaqs.lib.python.utils.jsonutils import JsonUtils
from orfaqs.lib.python.utils.perfutils import PerfProfiler


class ORFaqsCliExitCodes:
    SUCCESS = 0
    ERROR_REQUIRED_INPUT_NOT_SPECIFIED = -1


class ORFaqsCli(ABC):
    """OrfaqsCli"""

    _KWARGS_CTX_OBJECT_KEY = 'ctx'

    @staticmethod
    @abstractmethod
    def program_name() -> str:
        pass

    @classmethod
    def default_output_directory(cls) -> pathlib.Path:
        base_path = DirectoryUtils.make_path_object('./.orfaqs-apps')
        formatted_program_directory = (
            cls.program_name().replace(' ', '-').lower()
        )
        return base_path.joinpath(formatted_program_directory)

    @classmethod
    def _create_output_directory(
        cls,
        output_directory: str = None,
        job_id: str = None,
    ) -> pathlib.Path:
        #######################################################################
        # Create the local output directory path
        if output_directory is None:
            output_directory = './'

        output_directory = DirectoryUtils.make_path_object(output_directory)
        output_directory = output_directory.joinpath(
            cls.default_output_directory()
        )
        output_directory = DirectoryUtils.make_path_object(output_directory)
        if isinstance(job_id, str):
            output_directory = output_directory.joinpath(job_id)

        DirectoryUtils.mkdir_path(output_directory)
        return output_directory

    @staticmethod
    def launch_json_option_name() -> str:
        return 'launch_json'

    @staticmethod
    def _cli_params_to_args(params: any) -> any:
        def _format_dict(launch_args: dict) -> dict[str, any]:
            updated_map: dict[str, any] = {}
            for key, value in launch_args.items():
                key = ORFaqsCli._cli_params_to_args(key)
                if isinstance(value, dict):
                    updated_map[key] = _format_dict(value)
                else:
                    updated_map[key] = value

            return updated_map

        if isinstance(params, dict):
            params = _format_dict(params)
        elif isinstance(params, enum.Enum):
            params = ORFaqsCli._cli_params_to_args(params.value)
        elif isinstance(params, str):
            params = params.lower().replace('-', '_')

        return params

    @staticmethod
    def _process_ui_kwargs(
        launch_json_key: str = None,
        keep_launch_json: bool = False,
        remove_ctx: bool = True,
        **kwargs,
    ) -> dict[str, any]:
        if launch_json_key is None:
            launch_json_key = ORFaqsCli.launch_json_option_name()

        if kwargs.get(launch_json_key) is not None:
            launch_args: dict[str, any] = {}
            launch_json_path = kwargs[launch_json_key]
            launch_args = JsonUtils.read_json(launch_json_path)
            launch_args = ORFaqsCli._cli_params_to_args(launch_args)
            # Only replace input values that have not been set.
            for key, value in launch_args.items():
                if kwargs.get(key) is None:
                    kwargs[key] = value
                elif kwargs.get(key) is False:
                    kwargs[key] = value

        if not keep_launch_json:
            kwargs.pop(
                launch_json_key,
                None,
            )

        if remove_ctx:
            kwargs.pop(
                ORFaqsCli._KWARGS_CTX_OBJECT_KEY,
                None,
            )

        return kwargs

    @staticmethod
    def _new_app_typer(add_completion=True) -> typer.Typer:
        return typer.Typer(
            add_completion=add_completion,
            no_args_is_help=True,
        )

    @staticmethod
    def _job_id_annotation() -> tuple:
        return (
            str,
            typer.Option(
                help=(
                    'A string used to uniquely identify a set of results '
                    'generated by the tool. All results with the same job_id '
                    'share the same directory sub-folder.'
                ),
            ),
        )

    @staticmethod
    def _output_directory_annotation() -> tuple:
        return (
            str,
            typer.Option(
                help=(
                    'The output directory for exported files and results. If '
                    'the path does not exist, one will be created.'
                ),
            ),
        )

    @staticmethod
    def _export_path_annotation() -> tuple:
        return (
            str,
            typer.Option(
                help=(
                    'The explicit path where results are exported. Other '
                    'output directory paths and related options are ignored.'
                )
            ),
        )

    @staticmethod
    def _export_format_annotation(
        export_options: type,
    ) -> tuple:
        return (
            export_options,
            typer.Option(
                help=('Defines the exported format of the resulting data.')
            ),
        )

    @staticmethod
    def _enable_gpu_annotation() -> tuple:
        return (
            bool,
            typer.Option(
                '--enable-gpu',
                help=(
                    'Use available GPU resources for processing. If supported '
                    'GPU resources cannot be found, processing defaults to '
                    'the CPU.'
                ),
            ),
        )

    @staticmethod
    def _launch_json_annotation(
        function_type: Callable = typer.Option,
    ) -> tuple:
        return (
            str,
            function_type(
                help=(
                    'A JSON file specifying commands, arguments, and options to apply to '
                    "the program's session."
                )
            ),
        )

    @staticmethod
    @abstractmethod
    def _run(**kwargs):
        pass

    @classmethod
    def run(cls, **kwargs):
        perf_profiler = PerfProfiler(cls.__name__)
        function_name = cls.__class__.__qualname__
        perf_profiler.start_perf_timer(function_name)
        cls._run(**kwargs)
        perf_profiler.stop_perf_timer(function_name)
